// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxz2JK_Y3MOgA4jRVC89OQnda93MBve0I',
    appId: '1:450499877642:android:d6e388eac0a4ef1cc538f3',
    messagingSenderId: '450499877642',
    projectId: 'swimbuddy-app',
    storageBucket: 'swimbuddy-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnCWMZeO5jLxZ44wVp69_qO6cTdmzlVvs',
    appId: '1:450499877642:ios:57bdac362002700dc538f3',
    messagingSenderId: '450499877642',
    projectId: 'swimbuddy-app',
    storageBucket: 'swimbuddy-app.firebasestorage.app',
    androidClientId: '450499877642-2s9kbfl32bhsc5vcaefskp4n3bnr9448.apps.googleusercontent.com',
    iosClientId: '450499877642-n7lb6icqa83q3scen009uv60v4srrnrr.apps.googleusercontent.com',
    iosBundleId: 'com.jro.swimtracker',
  );
}
